- pom.xml
- src/test/resources/logback-access.xml
Når man tester lokalt kan det være fint med access-log i konsollet, slik det er mulig å følge med å se att requester faktiskt kommer inn i applikasjoner.
Eks når applikasjonen mottar en request som ikke genererer noe logg
`2020-05-07 17:30:59,671 [INFO ] [main] n.n.f.e.s.ApplicationLocalLauncherKt - [, , ] - Started ApplicationLocalLauncherKt in 4.586 seconds (JVM running for 5.19)
2020-05-07 17:31:00,880 Access-log 0:0:0:0:0:0:0:1 - - "GET /test HTTP/1.1" 404 0 "-" "curl/7.64.1"`
Når vi deployer til preprod/prod i nais så finnes access-log i kibana fra traefik-ingress-lb
Edit:
Dette burde egentligen virke med kun access-log fra logback, men fikk det ikke til å virke. Og det var denne avhengigheten som internettet mente att det virker 
http://logback.qos.ch/access.html
> Lagt til access-log for test-scope

- src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImpl.kt
En person som skulle søke om barnetilsyn hadde tre barn. To(tvillinger) var registrert som ikke boende hos ham (sjekket i gosys), en var registrert boende hos ham. Vi tror han fikk opp tvillingene, ikke barnet på 5 som var registrert hos ham. Klarer ikke gjenskape dette i test. 
Derfor: 
Legg på securelog i oppslagsservice for å kunne finne mulig feil i barn som vises for bruker. 
Logger ident + barn  (alder/harsammeadresse) vi får fra tps. 
ref:
https://jira.adeo.no/browse/FAGSYSTEM-131130
https://nav-it.slack.com/archives/G0104QDKZJQ/p1600856274001600
> Logging (tps hent person/barn)

- src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/BosituasjonMapper.kt
- src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SivilstandsplanerMapper.kt
- src/test/kotlin/no/nav/familie/ef/søknad/mapper/BosituasjonMapperTest.kt
Problem: Gjenbruk av bosituasjon.samboerdetaljer i UI/modell 
Løsning:
1. Hvis en søker har planer om å gifte seg i framtiden - ikke map samboerdetaler under bosituasjon
2. Hvis en bruker har planer om å gifte seg i framtiden -> map bosituasjon.samboerdetaljer til Sivilstandsplaner
Bedre løsning (på sikt) ikke gjenbruke modell, men splitte gjeldende situasjon og framtidsplaner i UI (litt større oppgave) 
Testes funksjonelt i preprod nå. Vil ikke merges før denne jobben er ferdig. 
Skal løse feil/bug: 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2720
> Bosituasjon gjenbrukes i framtidsplaner fix

- src/main/kotlin/no/nav/familie/ef/søknad/mapper/FeltMapperUtil.kt
- src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceLoggHjelper.kt
- src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImpl.kt
- src/test/kotlin/no/nav/familie/ef/søknad/mock/DokumentController.kt
- src/test/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceLoggHjelperTest.kt
- src/test/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImplTest.kt
Logger diff mellom tps og pdl. Logger ikke diff på de opplagte forskjellene på sivilstandstatus, men her kunne vi kanskje lagt inn flere. 
Logger ikke diff på navn barn selv om disse kommer i forskjellig rekkefølge fra tps. (split/sort) 
Testene som er lagt til er ikke veldig nøye på assertene, men de fungerer mest for å se at ting fungerer noenlunde. Hadde egentlig ikke tenkt å legge på tester, men det var lettere å endre på kode når jeg hadde med disse. 
Spørsmål -> flytte ut av service? 
to små endringer (throw Illegal => require) hører egentlig ikke med til dette.
> Logg diff tps pdl to secure

- src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceLoggHjelper.kt
Mini-pr: Mange unødvendige linjer i securelog av typen "Person: sivilstand = Tps: SEPR, Pdl: SEPARERT". Bytter om på mapping av SEPR og SEPA?
> Tps: SEPR, Pdl: SEPARERT

- src/main/kotlin/no/nav/familie/ef/søknad/api/OppslagController.kt
- src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagService.kt
- src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImpl.kt
- src/test/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImplTest.kt
Når vi merger denne vil vi ta i bruk pdl i prod. 
Vi fortsetter å logge diff mellom pdl og tps. Usikker på hvor stor verdi dette har?
Fjernet bruk av toggle: "familie.ef.soknad.bruk-pdl", så denne kan slettes fra unleash. 
=> Dersom vi ønsker å gå tilbake til tps må vi gjøre en redeploy.
> Bytt ut tps med pdl.

- pom.xml
- src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/FeltTyper.kt
- src/main/kotlin/no/nav/familie/ef/søknad/mapper/FeltMapperUtil.kt
- src/test/kotlin/no/nav/familie/ef/søknad/mapper/FeltMapperUtilKtTest.kt
- src/test/kotlin/no/nav/familie/ef/søknad/mapper/SkjemaMapperTest.kt
```familie-ef-soknad```  (frontend) sender allerede med svarid til ```ef-soknad-api```. Denne PR gjør at vi legger på svarid i søknadsobsjektet vi sender videre til ```ef-mottak```,  for tekstfelt.  Dette er for å kunne sammenligne på svarid istedenfor "svar verdi" i ```ef-sak-frontend```.
Vi ønsker f.eks. å kunne gjøre ca. dette:
```
switch (bosituasjon.delerDuBolig){
case EDelerbolig.borAlene:
return ABC
case EDelerbolig.borMedPartner:
return BAR
....
}
```
der bosituasjon.delerDuBolig lages basert på svarid
> Send svarid søknad

- pom.xml
Samlet noen dependabot oppdateringer
bump wiremock-jre8 from 2.28.1 to 2.29.1
bump commons-io from 2.10.0 to 2.11.0
bump kotlin.version from 1.5.20 to 1.5.21
bump jackson-module-kotlin from 2.12.3 to 2.12.4
bump mockk from 1.11.0 to 1.12.0
> bump spring-boot-starter-parent from 2.5.2 to 2.5.3

- src/main/kotlin/no/nav/familie/ef/søknad/mapper/SøkerinfoMapper.kt
- src/test/kotlin/no/nav/familie/ef/søknad/mapper/SøkerinfoMapperTest.kt
Hvis pdl returnerer tom liste uten noen sivilstand (heller ikke UOPPGITT) setter vi den til UOPPGITT.
> Sivilstand uoppgitt hvis liste fra pdl er tom

- src/main/kotlin/no/nav/familie/ef/søknad/api/FeatureToggleController.kt
Disse er fjeret fra frontend - ikke lenger i bruk. 
"familie.ef.soknad.sprakvelger",
"familie.ef.soknad.visSkalBehandlesINySaksbehandling
> Fjerner mer unødvendig toggles - ikke i bruk.

- pom.xml
- src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Medlemskap.kt
- src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/MedlemsskapsMapper.kt
- src/test/kotlin/no/nav/familie/ef/søknad/mapper/MedlemskapDtoMapperTest.kt
- src/test/resources/søknadDto.json
[FAVRO](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12261)
Søknad skal inneholde to nye felter for å registrere hvilket land søker oppholder seg i nå (`oppholdsland`) og hvilket land de oppholdt seg under et utenlandsopphold (`land`) og dette må mappes riktig i API-et slik at det blir sendt med videre. 
- Oppdatert kontrakter versjon
- Lagt de nye feltene inn i mapper
- Lagd egne tester for feltene
- Lastet opp i preprod og sjekket at feltene følger med til PDF når en søknad sendes inn med de nye feltene
- ef-soknad [PR 1245](https://github.com/navikt/familie-ef-soknad/pull/1245) (Lagt til de nye feltene)
- ef-sak PR (legger til de nye feltene i søknadsdata)
- familie-kontrakter [PR 744](https://github.com/navikt/familie-kontrakter/pull/774) …
> Skal ta i mot og mappe om informasjon om oppholdsland og land under utenlandsperiode

- pom.xml
Deploy + innsendt søknad ok i preprod.
bump maven-surefire-plugin from 2.22.2 to 3.0.0
bump logback-access-spring-boot-starter from 3.4.6 to 4.0.0
bump jacoco-maven-plugin from 0.8.9 to 0.8.10
bump token-validation-spring.version from 3.0.10 to 3.0.11
> Depandabot - bumps uke 19

- nais-dev.yaml
- nais-prod.yaml
Anbefaling fra NAIS om at CPU throttle fjernes fra pod, men beholdes for requests: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Artikkelen som det refereres til i meldingen fra NAIS beskriver godt hvorfor:
https://home.robusta.dev/blog/stop-using-cpu-limits
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12306)
> Fjerner CPU-limit

- nais-dev.yaml
- nais-prod.yaml
[Se diskusjon
](https://nav-it.slack.com/archives/CJN0STWB0/p1693384605818509)
>Restene av Loginservice forsvinner (etterhvert)
Til slutt minner vi om at de siste restene av Loginservice forsvinner i løpet av året. Om dere bruker noe av dette så bør dere begynne å legge planer om å slutte med det:
Ingressene [loginservice.intern.dev.nav.no](http://loginservice.intern.dev.nav.no/) og [loginservice.nav.no](http://loginservice.nav.no/) slutter å fungere
ConfigMap-et loginservice-idporten forsvinner
Cookien selvbetjening-idtoken blir ikke lenger satt
Deployet branch og testet innsendinga av søknad i preprod.
> Vil fjerne loginservice-idporten somikke er i bruk.

- src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/BarnMapper.kt
Barnepass ble ikke mappet slik at barn ikke ble huket av automatisk ved gjenbruk. Det er ønskelig at de blir det.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-17705)
> Map skal ha barnepass slik at barn blir automatisk huket av ved gjenbruk

- src/main/kotlin/no/nav/familie/ef/søknad/søknad/mapper/BarnMapper.kt
Feilen gjorde at det ikke var mulig å gjenbruke søknaden.
> Bruk fødselsdato til beregning av alder dersom fødselsnummer ikke finnes

- src/main/kotlin/no/nav/familie/ef/søknad/søknad/mapper/BarnMapper.kt
- Ønsker å sende med hvorforIkkeOppgi svarid fra api, dette blir nå utledet og sendt med.
- Annen forelder navn skal ikke sendes med hivs hvorforIkkeOppgiBegrunnelse har en verdi (det er valgt annet eller donor på annen forelder)
[Søknad](https://github.com/navikt/familie-ef-soknad/pull/1617)
> Hvorforikkeoppgi navn gjenbruk endring

- src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/featuretoggle/FeatureToggleController.kt
[Fjernet i frontend](https://github.com/navikt/familie-ef-soknad/pull/1634)
> Fjerner toggle for gjenbruk av BT søknad da dette alltid skal være på.

- src/main/kotlin/no/nav/familie/ef/søknad/søknad/mapper/BarnMapper.kt
- src/main/kotlin/no/nav/familie/ef/søknad/utils/FeltMapperUtil.kt
- src/test/kotlin/no/nav/familie/ef/søknad/søknad/mapper/BarnMapperTest.kt
- src/test/kotlin/no/nav/familie/ef/søknad/søknad/mapper/KontraktDto.kt
- src/test/kotlin/no/nav/familie/ef/søknad/utils/FeltMapperUtilKtTest.kt
Tidligere dukket det opp "Jeg har send inn denne dokumentasjonent il NAV tidligere" på alle barn, dersom én av barnene i søknaden ikke var født. Nå dukker "Jeg har send inn denne dokumentasjonent il NAV tidligere" (terminbekreftelsen) kun opp på barnet som ikke er født.
Gammelt:
Nytt:
> spm om terminbekreftelse kommer kun ved ufødt barn

- src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/config/MottakConfig.kt
- src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/featuretoggle/FeatureToggleController.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/MottakClient.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadKvitteringController.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadService.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/dto/SistInnsendteSøknadDto.kt
Vi ønsker å vite om bruker har sendt inn en søknad når bruker starter søknadsflyten. Dette gjør vi i håp om å informere bruker om at det allerede finnes en søknad, noe som kanskje stopper bruker fra å sende en ny, men ellers lik søknad. Det skal fortsatt være mulig å sende en til søknad, men håpet er å redusere søknader som er like. 
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23469).
Denne PRen er en del av en bredere oppgave og depender på denne → [PRen i familie-ef-mottak](https://github.com/navikt/familie-ef-mottak/pull/1229).
* Vi planlegger å feature toggle i front-end der vi enkelt ikke gjør kallet med mindre feature toggle er skrudd på.
* Vi har ikke utbedret tekster eller hva som …
> Feature - hent ferskeste søknader per stønad når bruker starter søknadflyten

- pom.xml
- src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/config/MottakConfig.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/MottakClient.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadKvitteringController.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadService.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/dto/SistInnsendteSøknadDto.kt
Denne PRen har som hensikt å hente ut `SistInnsendtSøknadDto` fra `ef-kontrakter` da dette objektet brukes nå av flere apper. Vi har også mappet om typen i `SistInnsendtSøknadDto` fra `String` til `StønadType` i håp om at det skal bli tydeligere i front end.
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23469).
Denne PRen er en del av en bredre oppgave og depender på denne → [PRen](https://github.com/navikt/familie-ef-mottak/pull/1232) i `familie-ef-mottak`.
Denne featuren er feature-togglet i front-end.
> Feature - SistInnsendtSøknadDto hentes fra kontrakter

- src/main/kotlin/no/nav/familie/ef/søknad/person/dto/PdlPerson.kt
- src/main/kotlin/no/nav/familie/ef/søknad/person/mapper/SøkerinfoMapper.kt
- src/main/resources/pdl/søker.graphql
- src/test/kotlin/no/nav/familie/ef/søknad/person/PdlClientConfig.kt
- src/test/kotlin/no/nav/familie/ef/søknad/person/PdlTestdata.kt
- src/test/kotlin/no/nav/familie/ef/søknad/person/mapper/SøkerinfoMapperTest.kt
Tanken var at kun gjeldende statsborgerskap skulle vises i søknads pdf, ble reagert på dobbelt statsborgerskap hvor ett av statsborgerskapene ikke hadde en start dato. Viser seg at gyldigFraOgMed som hentes fra PDL ikke alltid er tilgjengelig og derfor er ikke nødvendvis dette et tegn på at statsborgerskapet ikke er gyldig. Trengs dermed ikke endringer fra orginalt oppsett. Derimot må det fjernes noen endringer gjort tidligere for testing av dette med logging.
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24389).
> SøknadsPDF - Vise kun gjeldende statsborgerskap

- src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadController.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadService.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/domain/SvarId.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/domain/SvarIdValidator.kt
- src/main/kotlin/no/nav/familie/ef/søknad/søknad/mapper/SøknadSkolepengerMapper.kt
- src/test/kotlin/no/nav/familie/ef/søknad/mock/SøknadDto.kt
- src/test/kotlin/no/nav/familie/ef/søknad/søknad/SøknadServiceTest.kt
- src/test/kotlin/no/nav/familie/ef/søknad/søknad/domain/SvarIdValidatorTest.kt
- src/test/kotlin/no/nav/familie/ef/søknad/søknad/mapper/SøknadBarnetilsynMapperTest.kt
- src/test/resources/barnetilsyn/Barnetilsynsøknad.json
- src/test/resources/barnetilsyn/BarnetilsynsøknadDto.json
Sørger for at bruker ikke kan gjenbruke forrige søknad dersom det finnes ugyldige svarIds, altså verdier som ikke finnes i SvarId enum som er opprettet. Det må fortsatt undersøkes hvorfor disse ugyldige verdiene oppstår (typisk "null" som string), lager en egen Favro-oppgave for dette.
Testet med testperson: 30438747490 hvor "null" ble satt som svarId på spørsmålet om foreldre møtes. 
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25738)
> Valider svar id til gjenbruk
