navikt/familie-ef-soknad-api

src/main/kotlin/no/nav/familie/ef/søknad/api/PingController.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/CorsProperties.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/WebConfig.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml
Kun CORS config for dev/preprod 
I CorsProperties: var allowedOrigins: Array<String> - finnes det en bedre måte?
=> Web configuration

app-preprod.yaml, src/main/kotlin/no/nav/familie/ef/søknad/api/SøknadController.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/MottakConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/integration/SøknadClient.kt, src/main/resources/application-dev.yml, src/main/resources/application-preprod.yml, src/main/resources/application.yml
- `familie-ef-soknad`, `familie-ef-soknad-api` og `familie-ef-mottak` kan nå ta i bruk vault (https://github.com/navikt/vault-iac/pull/602). 
- Satt opp gateway og testet kall fra api til mottak
- Se kommentarer i pr og kom gjerne med innspill.
Mer detaljer om hvordan finnes i checklist her (spør gjerne om det er noe dere vil vite mer om :) ): https://trello.com/c/kvBfQRr9/98-kommunikasjon-mellom-sbs-og-ffs
=> Sonekryssing

src/main/kotlin/no/nav/familie/ef/søknad/api/FeatureToggleController.kt
Tilgjengeliggjør et map med alle funksjonsbrytere for frontend
=> Legg til endepunkt for å hente alle funksjonsbrytere

src/main/kotlin/no/nav/familie/ef/søknad/api/PingController.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/SøknadController.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/MottakConfig.kt, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/søknad/integrationTest/PingControllerApiIntegrationTest.kt
- Endring i endepunkt (implisitt at post søknad er innsending?)
- Litt rydding i cors med Mattis
- Trenger ikke bruke land url ved kjøring lokalt
=> endepunktsendringer og litt opprydding

src/main/kotlin/no/nav/familie/ef/søknad/api/AutentiseringController.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/PingController.kt, src/test/kotlin/no/nav/familie/ef/søknad/integrationTest/AutentiseringControllerApiIntegrationTest.kt
Fjernet også protection på ping-endepunkt som tidligere ble brukt til dette
=> Legg til endepunkt for å sjekke om man er autentisert

.circleci/config.yml, .m2/maven-settings.xml, pom.xml
Oppdatert secrets med token og projecktKey.
=> Sonarcloud

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/Application.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/filter/CORSResponseFilter.kt
Bumper dependencies foreslått av dependabot og legger til `@ConfigurationPropertiesScan` for at appen skal kjøre, etter at det ble opt-in i Spring Boot 2.2.
=> Bump dependencies

src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Adresse.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Barn.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/BegrunnelseForSøknad.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Bosituasjon.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Medlemskap.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Person.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Sivilstatus.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Søker.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøkerBorPåRegistrertAdresse.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøkerBosattINorgeSisteTreÅr.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøkerDelerBoligMedAndreVoksne.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøkerGiftIUtlandet.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøkerOppholderSegINorge.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøkerSeparertEllerSkiltIUtlandet.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøknadDto.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøknadInput.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/SøknadMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/api/SøknadInputControllerTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SøknadInputMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/SøknadsControllerMock.kt
Lagt til manglende dto'er som vi får fra UI + en test (deserialisering)
=> Mapping siste versjon av data fra ui

src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Medlemskap.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/MedlemsskapsMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SøknadMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/api/SøknadInputControllerTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/MedlemskapDtoMapperTest.kt, src/test/resources/søknadDto.json
Map medlemskap + test. 
Fjernet serialiseringstest - dekket av andre tester.
Fjerner flyktingstatus i annen PR.
=> Map medlemskap + test. 

src/main/kotlin/no/nav/familie/ef/søknad/config/MottakConfig.kt, src/main/resources/application-dev.yml
=> Vil fikse bug: path lagt til uten slash mot mottak

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Aktivitet.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Barn.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Bosituasjon.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Medlemskap.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Situasjon.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøknadDto.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/AktivitetsMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/BosituasjonMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SituasjonsMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SivilstandsplanerMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SøknadMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/AktivitetsMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/ArbeidsforholdMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/ArbeidssøkerMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SituasjonMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/UnderUtdanningMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/TpsInnsynMockController.kt, src/test/resources/bositiasjonSamboer.json, src/test/resources/sivilstandsplaner.json, src/test/resources/søknadDto.json
Ikke den mest spennende pull requesten. Kanskje lurt om vi venter med kommentarer av type "hva skal variabelen hete" til vi kan sette oss ned sammen (frontend/backend) og ta en full gjennomgang, men dersom du ser noe opplagt - noter det gjerne :)
=> Map situasjon og aktivitet/utdanning

src/main/kotlin/no/nav/familie/ef/søknad/api/RegistrerArbeidsaktivitetController.kt
Bruk feature toggle - opprettet i unleash, testet at autentisering virker
=> Legger til registrer at bruker er arbeidssøker endepunkt

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/RegistrerArbeidsaktivitetController.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/SkjemaMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/SkjemaService.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SkjemaMapperTest.kt
Testet i preprod med swagger - fungerer. 
Fjerner @Component på Skjemamapper
Fjerner unødvendige linjer i Controller
Ikke helt fornøyd med uthenting av navn - henter ut litt mye jeg ikke trenger i service  
alternativer: 
bruke klient direkte i controller
legge til en service for å hente ut bare person 
Andre? 
Hva synest dere blir best?
=> Legg til innsenders navn på skjema 15-08.01.

.github/workflows/build.yml
=> Push til master bygger til prod. Push til alt bortsett fra master deployer dev

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/RegistrerArbeidsaktivitetController.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/SøknadController.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/Kvittering.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/KvitteringMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/SkjemaMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SøknadMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/SkjemaService.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/SøknadService.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/SøknadServiceImpl.kt, src/test/kotlin/no/nav/familie/ef/søknad/api/SøknadInputControllerTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/KvitteringDtoMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SkjemaMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SøknadInputMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/SøknadsControllerMock.kt
Forslag - kom gjerne med innspill
=> Kontrakter oppdatering innsendingstidspunkt

src/main/kotlin/no/nav/familie/ef/søknad/mapper/SkjemaMapper.kt
=> Legg til 15-08.01 på skjema i tittel over personalia

src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Adresse.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Barn.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Bosituasjon.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Situasjon.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Sivilstatus.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Søker.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/BarnMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/PersonMinimumMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SivilstandsdetaljerMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SivilstandsdetaljerMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/BarnMapperTest.kt, src/test/resources/bositiasjonSamboer.json, src/test/resources/sivilstandsplaner.json, src/test/resources/søknadDto.json
Work in progress - muliggjør innsending (av en versjon av søknaden) 
Merket felter vi må jobbe mer med med TODO.
=> Mapping juni brukertest

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Aktivitet.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/FeltTyper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/FeltMapperUtil.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/AktivitetsMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/AktivitetsMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/ArbeidsforholdMapperTest.kt, src/test/resources/søknadDto.json
Lagt til Aksjeselskap-mapping + tester
Lagt til HeltallFelt og feltmapper-extension
=> Mapping - lagt til aksjeselskap

src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Aktivitet.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/FeltMapperUtil.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/AktivitetsMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SøknadTest.kt, src/test/resources/sisteinnspurt/feilfraEivind.json, src/test/resources/sisteinnspurt/søknadMedUgyldigFødselsnummer.json
Gjør om strenger som skal være heltall om til heltall - selv om verdier fra UI er med desimaler.
=> Desimal string til int

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Barn.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Bosituasjon.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/BarnMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/BosituasjonMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/PersonMinimumMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SivilstandsplanerMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SivilstandsplanerMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SøknadTest.kt, src/test/resources/bositiasjonSamboer.json, src/test/resources/sisteinnspurt/feilfraEivind.json, src/test/resources/sisteinnspurt/fnrTilIdent.json, src/test/resources/sisteinnspurt/identTest3.json, src/test/resources/sisteinnspurt/nyttBarnFeil.json, src/test/resources/sisteinnspurt/testFntIdent.json, src/test/resources/sisteinnspurt/testfeil.json, src/test/resources/sisteinnspurt/underUtanningFeil.json, src/test/resources/sivilstandsplaner.json, src/test/resources/søknadDto.json
Merges når ui endringer er klare.
=> Lagt til dato flyttet fra hverandre og byttet til "ident" på dto'er.

src/main/kotlin/no/nav/familie/ef/søknad/api/OppslagController.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Adresse.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/tps/Adresse.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/FamilieIntegrasjonerConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/integration/FamilieIntegrasjonerClient.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/SøkerinfoMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/PersonaliaMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SøknadMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/KodeverkService.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagService.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImpl.kt, src/main/resources/application-local.yml, src/test/kotlin/no/nav/familie/ef/søknad/ApplicationLocalLauncher.kt, src/test/kotlin/no/nav/familie/ef/søknad/api/OppslagControllerTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/KontraktDto.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SøkerinfoMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/DokumentController.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/FamilieIntegrasjonerMock.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/SøknadDto.kt, src/test/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImplTest.kt, src/test/resources/søknadDto.json
løser https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1562
=> Send med poststed til frontend

src/main/kotlin/no/nav/familie/ef/søknad/mapper/SøkerinfoMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/SøkerinfoMapperTest.kt
=> Legg til poststed kall mot integrasjoner

README.md, pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/Application.kt, src/test/kotlin/no/nav/familie/ef/søknad/ApplicationLocalLauncher.kt
Obs; ny swagger-url: .../swagger-ui/index.html
=> Oppgradert springfox v3.0.0

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SøknadBarnetilsynMapper.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1876
=> Slettet dokumentasjon for tidligere fakturaer

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SituasjonsMapper.kt
Hardkoder alternativer under situasjon her. Legger inn mulighet for å legge inn dette fra UI på Onsdag.
=> Kontrakt pdf oppdatering

src/main/kotlin/no/nav/familie/ef/søknad/mapper/FeltMapperUtil.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SituasjonsMapper.kt, src/test/resources/søknadDto.json
Legg til alternativer i tilSøknadsfelt()
NB! https://github.com/navikt/familie-ef-soknad/pull/375 må merges først.
=> Legg til alternativer i tilSøknadsfelt()

src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImpl.kt, src/test/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImplTest.kt
Noe vi kunne testet i prod før vi begynner å bruke pdl for å hente personopplysninger?
=> Pdl - hent ut navn, bruk i ui

src/main/kotlin/no/nav/familie/ef/søknad/api/FeatureToggleController.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/TpsInnsynMockController.kt
=> Legg til feature toggle for språkvelger

src/main/kotlin/no/nav/familie/ef/søknad/config/FamilieDokumentConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/health/FamilieDokumentHealthIndicator.kt, src/main/kotlin/no/nav/familie/ef/søknad/health/FamilieDokumentSbsHealthIndicator.kt, src/main/kotlin/no/nav/familie/ef/søknad/integration/FamilieDokumentSbsClient.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/DokumentServiceImpl.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/søknad/service/DokumentServiceImplTest.kt
Notere att den er featuretogglet, hvis feature ikke er enabled, så henter den fra SBS.
Midlertidlig kommer man hente fra gcp, hvis den ikke finnes der så henter vi fra sbs. Når vi gått over helt til GCP kan koden fjernes
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-361
=> Gå over til å bruke dokument-gcp

src/test/kotlin/no/nav/familie/ef/søknad/service/KodeverkServiceTest.kt
Kjør på jupiter (ikke vintage)
=> Test jupiter

src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceLoggHjelper.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImpl.kt
Legg til litt flere mappinger for sivilstand. Antar at rekkefølge (pdl/tps) er riktig til metoden som mottar. (Kode skal ikke leve lenge eller brukes av andre)
=> Tps/pdl forbedret logging (flere mappinger mellom tps -> pdl).

src/main/kotlin/no/nav/familie/ef/søknad/integration/PdlStsClient.kt, src/main/kotlin/no/nav/familie/ef/søknad/integration/dto/pdl/PdlPerson.kt, src/test/kotlin/no/nav/familie/ef/søknad/integration/PdlStsClientTest.kt, src/test/resources/pdl/pdlBolkErrorResponse.json, src/test/resources/pdl/pdlBolkErrorResponse_nullData.json
Tok med test av null i bolk-oppslag, etter kommentarer på https://github.com/navikt/familie-ef-sak/pull/388
=> Data i bolkoppslag kan være null

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/SøknadBarnetilsynController.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/Situasjon.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/FeatureToggleConfig.kt, src/test/kotlin/no/nav/familie/ef/søknad/ApplicationLocalLauncher.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/MottakClientMock.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/PdlClientConfig.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/StsPdlClientConfig.kt
(dummy-feature-toggle returnerer også false for feilsituasjon)
=> Litt rydding + bedre mocking av PDL data (inkludert barn) /  mottak

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøknadBarnetilsynDto.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøknadOvergangsstønadDto.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/SøknadSkolepengerDto.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SøknadBarnetilsynMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SøknadOvergangsstønadMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/SøknadSkolepengerMapper.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4340
Denne endring gjør det mulig å endre fra frontend om man ønsker å ha med automatisk journalføring eller ikke
=> Flagg for skalBehandlesINySaksbehandling

.github/workflows/deploy-dev.yml
Ikke deploy til dev/preprod on push
=> Ikke deploy til dev/preprod on push

pom.xml
1. spring-boot-starter-parent from 2.4.4 to 2.4.5
2. jackson-module-kotlin from 2.12.2 to 2.12.3
3. felles.version -> 1.20210419103325_d044927
4. token-validation-spring.version from 1.3.4 to 1.3.7
5. sonar-maven-plugin from 3.8.0.2131 to 3.9.0.2155
~~6. kotlin.version from 1.4.32 to 1.5.0~~
7. kontrakter.version to 2.0_20210505062042_ac23906
Deployet til preprod. Sendt inn søknad = ok.
=> Dependabot samplepr

src/main/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImpl.kt, src/test/kotlin/no/nav/familie/ef/søknad/service/OppslagServiceServiceImplTest.kt
Dersom vi ikke kjenner fødselsdato for et barn skal vi ikke filtrere bort dette for visning i søknad.
=> Ikke filtrer bort barn uten fødselsdato

pom.xml
Vil oppdatere Unleash, commons-io, kotlin og spring-boot-starter-parent
Testet en innsending i preprod - alt ok.
=> Dependabot samlebranch

pom.xml
Test i preprod = ok. 
build(deps): bump kotlin.version from 1.5.10 to 1.5.20  dependencies
build(deps): bump spring-boot-starter-parent from 2.5.0 to 2.5.2  dependencies
build(deps): bump token-validation-spring.version from 1.3.7 to 1.3.8  dependencies
build(deps): bump commons-io from 2.9.0 to 2.10.0  dependencies
build(deps): bump unleash-client-java from 4.3.0 to 4.4.0  dependencies
=> Dependabot samlet

nais-dev.yaml, src/main/resources/application-dev.yml
Legge til ingress for å kunne nås fra dev.nav.no
Løser en utfordring med token domain for ettersending applikasjonen
=> Legge til ingress for å kunne nås fra dev.nav.no

src/main/kotlin/no/nav/familie/ef/søknad/api/dto/søknadsdialog/EttersendingDto.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/EttersendingMapper.kt
Data typen for dokumentasjonsbehov som kommer inn i appen er definert i kontrakter mens videre i appen er det definert i søknad.api.dto.søknadsdialog.
=> endret typer for dokumentasjonsbehov

src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/EttersendingMapper.kt
sender med vedlegg fra konteksfri innsening for søknad og innsending uten søknad i vedleggsliste
=> Oppdatert ettersendingsmapper

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/EttersendingController.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/ettersending/EttersendingDto.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/ettersending/EttersendingForSøknad.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/ettersending/EttersendingResponseData.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/ettersending/EttersendingUtenSøknad.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/dto/ettersending/Innsending.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/MottakConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/integration/EttersendingRequestData.kt, src/main/kotlin/no/nav/familie/ef/søknad/integration/SøknadClient.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/EttersendingMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/EttersendingService.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/MottakClientMock.kt
- Laget endepunkt for å hente tidligere ettersendinger
- Oppdatert typer fra kontrakter
=> Hent ettersending

pom.xml, src/test/kotlin/no/nav/familie/ef/søknad/mock/MottakClientMock.kt
Avventer merging til frontend er klart.
=> Bumper kontrakter og oppdaterer mockdata for ettersending

nais-dev.yaml, nais-prod.yaml
Jeg tror vi må legge til azure først, og sen la pdl-api deployes på nytt sånn att vi får tilgang til pdl-api.. 
Når pdl-api sen har deployets kommer jeg teste https://github.com/navikt/familie-ef-soknad-api/compare/tokenx-pdl-dokument?expand=1
Nå får vi denne feilen https://logs.adeo.no/app/discover#/doc/tjenestekall-*/tjenestekall-team-teamfamilie-test-000015?id=4FiELHsBkiPwGYa3b3j9
=> Må legge till azure i nais sånn att vi kan få tilgang til pdl

src/main/resources/application.yml
Trengtes for https://github.com/navikt/familie-ef-soknad-api/pull/510
=> Trenger å sette inn override av bean definition for OAuth2HttpClient

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/EttersendingController.kt, src/main/kotlin/no/nav/familie/ef/søknad/integration/SøknadClient.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/EttersendingMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/service/EttersendingService.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/EttersendingMapperTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/MottakClientMock.kt
Kjører SNAPSHOT-versjon mot kontrakter frem til kontrakter er godkjent.
=> endret modell for ettersending

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/537
- https://github.com/navikt/familie-ef-soknad-api/pull/536
- https://github.com/navikt/familie-ef-soknad-api/pull/527
=> Dependabot oppdateringer 20211004-091034

nais-dev.yaml, nais-prod.yaml, src/main/kotlin/no/nav/familie/ef/søknad/integration/SøknadClient.kt
Featuretoggle for hvilket miljø ef-soknad-api skal gå mot: https://unleash.nais.io/#/features/strategies/familie.ef.soknad.api.gcp
Denne er deaktivert, og skal aktiveres når ef-mottak er migrert til gcp
=> Feature toggle mottak gcp

src/main/kotlin/no/nav/familie/ef/søknad/mapper/SøkerinfoMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/ApplicationLocalLauncher.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/IntegrasjonerMock.kt
Mockk integrasjoner unngå error mot familie integrasjoner (health check)
=> Mockk integrasjoner ping error oppstart

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/integrasjonsTest.yml, pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/579
- https://github.com/navikt/familie-ef-soknad-api/pull/578
- https://github.com/navikt/familie-ef-soknad-api/pull/576
- https://github.com/navikt/familie-ef-soknad-api/pull/574
- https://github.com/navikt/familie-ef-soknad-api/pull/569
=> Dependabot oppdateringer 20211206-101537

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/589
- https://github.com/navikt/familie-ef-soknad-api/pull/588
- https://github.com/navikt/familie-ef-soknad-api/pull/587
- https://github.com/navikt/familie-ef-soknad-api/pull/586
- https://github.com/navikt/familie-ef-soknad-api/pull/584
=> Dependabot oppdateringer 20220103-093355

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/592
- https://github.com/navikt/familie-ef-soknad-api/pull/591
=> Dependabot oppdateringer 20220104-094213

src/main/kotlin/no/nav/familie/ef/søknad/integration/SøknadClient.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/resources/application-local.yml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7659
=> Tar i bruk Q1 i dev

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/601
- https://github.com/navikt/familie-ef-soknad-api/pull/600
- https://github.com/navikt/familie-ef-soknad-api/pull/599
=> Dependabot oppdateringer 20220124-083219

src/main/kotlin/no/nav/familie/ef/søknad/api/SøknadSkolepengerController.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/Mapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/MapperMedVedlegg.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/BarnMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/PersonMinimumMapper.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/PersonaliaMapper.kt
Tiltak etter ROS - fjerner her unødvendig logging. 
Tar kanskje bort litt mye nå, men det er lenge siden vi har hatt bruk for disse til debugging/feilretting. Ved behov kan vi legge inn dette senere.
=> Vil fjerne unødvendig logging av persondata til securelogs.

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/612
- https://github.com/navikt/familie-ef-soknad-api/pull/611
- https://github.com/navikt/familie-ef-soknad-api/pull/607
=> Dependabot oppdateringer 20220228-081241

src/main/kotlin/no/nav/familie/ef/søknad/api/FeatureToggleController.kt
Hører til denne [frontend-PRen](https://github.com/navikt/familie-ef-soknad/pull/829).
=> Legg til funksjonsbryter for Nynorsk-dropdown

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/integrasjonsTest.yml, pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/620
- https://github.com/navikt/familie-ef-soknad-api/pull/619
- https://github.com/navikt/familie-ef-soknad-api/pull/618
- https://github.com/navikt/familie-ef-soknad-api/pull/616
=> Dependabot oppdateringer 20220307-082609

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/624
- https://github.com/navikt/familie-ef-soknad-api/pull/623
=> Dependabot oppdateringer 20220314-081544

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/628
- https://github.com/navikt/familie-ef-soknad-api/pull/627
=> Dependabot oppdateringer 20220321-083754

pom.xml
Funker dette? (ref dependabot PR https://github.com/navikt/familie-ef-soknad-api/pull/554)
=> Rakugakibox til akkinoc logback access

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/637
- https://github.com/navikt/familie-ef-soknad-api/pull/636
- https://github.com/navikt/familie-ef-soknad-api/pull/635
- https://github.com/navikt/familie-ef-soknad-api/pull/634
=> Dependabot oppdateringer 20220328-082743

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/645
- https://github.com/navikt/familie-ef-soknad-api/pull/644
- https://github.com/navikt/familie-ef-soknad-api/pull/643
- https://github.com/navikt/familie-ef-soknad-api/pull/642
=> Dependabot oppdateringer 20220404-081930

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/integrasjonsTest.yml, pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/654
- https://github.com/navikt/familie-ef-soknad-api/pull/653
- https://github.com/navikt/familie-ef-soknad-api/pull/652
- https://github.com/navikt/familie-ef-soknad-api/pull/649
- https://github.com/navikt/familie-ef-soknad-api/pull/648
- https://github.com/navikt/familie-ef-soknad-api/pull/647
=> Dependabot oppdateringer 20220419-083326

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/659
- https://github.com/navikt/familie-ef-soknad-api/pull/658
=> Dependabot oppdateringer 20220425-081811

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/669
- https://github.com/navikt/familie-ef-soknad-api/pull/667
=> Dependabot oppdateringer 20220509-080843

src/main/kotlin/no/nav/familie/ef/søknad/mapper/FeltMapperUtil.kt, src/main/kotlin/no/nav/familie/ef/søknad/mapper/kontrakt/AktivitetsMapper.kt, src/test/kotlin/no/nav/familie/ef/søknad/mapper/AktivitetsMapperTest.kt
Vi hadde en midlertidig fiks her pga manglende validering i frontend. Det er lagt til validering i front for ganske lenge siden.
=> Skal ikke gjøre om blank (arbeidsmengde) til tallet 0

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/716
- https://github.com/navikt/familie-ef-soknad-api/pull/715
- https://github.com/navikt/familie-ef-soknad-api/pull/713
- https://github.com/navikt/familie-ef-soknad-api/pull/712
- https://github.com/navikt/familie-ef-soknad-api/pull/711
- https://github.com/navikt/familie-ef-soknad-api/pull/707
- https://github.com/navikt/familie-ef-soknad-api/pull/704
=> Dependabot oppdateringer 20220801-135347

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/730
- https://github.com/navikt/familie-ef-soknad-api/pull/729
- https://github.com/navikt/familie-ef-soknad-api/pull/728
- https://github.com/navikt/familie-ef-soknad-api/pull/727
- https://github.com/navikt/familie-ef-soknad-api/pull/724
- https://github.com/navikt/familie-ef-soknad-api/pull/718
=> Dependabot oppdateringer 20220822-090012

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-soknad-api/pull/750
- https://github.com/navikt/familie-ef-soknad-api/pull/748
- https://github.com/navikt/familie-ef-soknad-api/pull/746
- https://github.com/navikt/familie-ef-soknad-api/pull/744
- https://github.com/navikt/familie-ef-soknad-api/pull/742
- https://github.com/navikt/familie-ef-soknad-api/pull/741
- https://github.com/navikt/familie-ef-soknad-api/pull/738
- https://github.com/navikt/familie-ef-soknad-api/pull/732
=> Dependabot oppdateringer 20220926-125250

src/main/resources/application-dev.yml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10604
=> Tar i bruk q2

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/featuretoggle/ByEnvironmentStrategy.kt, src/test/kotlin/no/nav/familie/ef/søknad/api/FeatureToggleControllerIntegrationTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/api/FeatureToggleControllerTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/featuretoggle/ByEnvironmentStrategyTest.kt
Testet i dev.
Nynorsk toggel på i dev: 
Av:
=> Bytt unleash klient

pom.xml, src/main/kotlin/no/nav/familie/ef/søknad/api/ApiExceptionHandler.kt, src/main/kotlin/no/nav/familie/ef/søknad/api/filter/CORSResponseFilter.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/ApplicationConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/CorsProperties.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/FamilieIntegrasjonerConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/HealthIndicatorConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/MottakConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/config/RegelverkConfig.kt, src/main/resources/application.yml, src/main/resources/logback-spring.xml, src/test/kotlin/no/nav/familie/ef/søknad/api/SøknadBarnetilsynControllerTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/api/SøknadOvergangsstønadControllerTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/api/SøknadSkolepengerControllerTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-11344
Anbefaler å gå igjennom  
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide
* https://github.com/navikt/familie-felles/pull/661
=> Spring boot 3

README.md, nais-dev.yaml
* Bruker service discovery fra frontend
* Legger til ny ingress for intern bruk/swagger
=> Fjerner ingresser som ikke lengre er i bruk

src/main/kotlin/no/nav/familie/ef/søknad/api/FeatureToggleController.kt
Toggelen ble brukt til å teste i prod
=> Fjerner toggle brukt til testing i prod

.github/dependabot.yml
=> Vil oppdatere dependabot til å bruke READER_TOKEN

src/main/kotlin/no/nav/familie/ef/søknad/api/FeatureToggleController.kt
Vil legge til toggle - 'familie.ef.soknad.validerbosituasjon' (skal brukes i frontend)
=> Vil legge til toggle - 'familie.ef.soknad.validerbosituasjon'

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/integrasjonsTest.yml, Dockerfile, pom.xml
=> Oppdater - java21

.github/workflows/codeql-analysis.yml
=> Legg til codeql

src/main/kotlin/no/nav/familie/ef/søknad/minside/JournalpostService.kt, src/test/kotlin/no/nav/familie/ef/søknad/minside/JournalpostControllerTest.kt
Har gjort avsjekk med Mirja og det ser trygt ut å legge ut disse. Blankettene inngår IKKE blant disse notatene
=> Skal vise journalpostnotater på minside

src/main/kotlin/no/nav/familie/ef/søknad/minside/JournalpostService.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadBarnetilsynController.kt
Vanskelig å feilsøke da alle søknader er kryptert i basen, legger derfor til logging.
=> Logg forrige søknad

src/test/resources/minside/dummy-journalposter.json
Viktig for å få frontend til å vise riktig ved lokal kjøring :)
=> retter på skrivefeil i testdata for dokumenter sine titler

src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/featuretoggle/FeatureToggleController.kt
Vil rydde bort toggle som ikke er i bruk.
=> Vil fjerne toggle validerbosituasjon

src/main/kotlin/no/nav/familie/ef/søknad/minside/JournalpostService.kt
=> Ønsker å sortere journalposter etter dato slik at nyeste vises først.

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, pom.xml
GHCR ga problemer med håndtering av image, og nais-teamet jobbet derfor med alternativ løsning. Løsningen ble GAR og det er dermed anbefalt å migrere over for en bedre brukeropplevelse.
https://nav-it.slack.com/archives/C5KUST8N6/p1678189735336849?thread_ts=1678188149.218519&cid=C5KUST8N6
https://docs.nais.io/build/how-to/oci-migration/
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-21284)
=> Migrerer til GAR

src/main/kotlin/no/nav/familie/ef/søknad/person/OppslagServiceServiceImpl.kt, src/main/kotlin/no/nav/familie/ef/søknad/person/dto/PdlPerson.kt, src/main/kotlin/no/nav/familie/ef/søknad/person/mapper/SøkerinfoMapper.kt, src/main/resources/pdl/barn.graphql, src/main/resources/pdl/pdl-api-schema.graphql, src/test/kotlin/no/nav/familie/ef/søknad/person/OppslagServiceServiceImplTest.kt, src/test/kotlin/no/nav/familie/ef/søknad/person/PdlApp2AppClientConfig.kt, src/test/kotlin/no/nav/familie/ef/søknad/person/PdlTestdata.kt, src/test/kotlin/no/nav/familie/ef/søknad/person/mapper/SøkerinfoMapperTest.kt, src/test/resources/pdl/barn.json
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-21643
=> Endrer Fødsel til Fødselsdato da Fødsel fases ut av PDL

src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/config/MottakConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/MottakClient.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadKvitteringController.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadService.kt, src/test/kotlin/no/nav/familie/ef/søknad/søknad/SøknadKvitteringControllerTest.kt
**Endringer:**
- Oppdatert testene i SøknadKvitteringControllerTest til å bruke riktig sendInn funksjoner
- SøknadsService: Oppdatert med nye SendInnfunksjoner for barnetilsyn og skolpenger
- Mottaksclient oppdater med nye sendInn funksjoner
- Mottakconfig: Riktig URI/PAATH for barnetilsyn og skolepenegr mot mottak
=> Barnetilsyn og skolepenger bruker vår flyt

src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/config/MottakConfig.kt
Pga. https://github.com/navikt/familie-ef-mottak/pull/1181 må endtepunktene oppdateres
=> Oppdatert uri fra /pdf-kvittering til /soknadskvittering

src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/config/MottakConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/MottakClient.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadKvitteringController.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadService.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/mapper/SkjemaMapper.kt
Endringer:
- Post endepunkt "arbeidssoker" i SøknadskvitteringController
- sendInn funksjon i Søknadservice for arbeidsøkerskjema
=> Arbeidssøkerskjema i ny flyt.

src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/config/MottakConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/MottakClient.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadKvitteringController.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadService.kt
Går mot nytt endepunkt i ny flyt
=> Oppdatere endepunkter mot barnetilsyn/forrige

src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadKvitteringController.kt
=> Fiks for GetMapping ved henting av sist innsendte søknader. 

pom.xml
Mirja ønkser at spørsmålet om du er i arbeide kommer først
=> Oppdater-kontrakter-for-å-endre-aktivitet-rekkefølgen

src/main/kotlin/no/nav/familie/ef/søknad/person/dto/PdlPerson.kt, src/main/kotlin/no/nav/familie/ef/søknad/person/mapper/SøkerinfoMapper.kt, src/main/resources/pdl/søker.graphql, src/test/kotlin/no/nav/familie/ef/søknad/person/PdlClientConfig.kt, src/test/kotlin/no/nav/familie/ef/søknad/person/PdlTestdata.kt
Logger for å avgjøre hva som gjør et statsborgerskap gjeldende/historisk eller ikke
=> Legge til logging for historisk statsborgerskap

.deploy/nais-dev.yaml
https://nav-it.slack.com/archives/C60FFACN5/p1740985537800509
=> Skal bytte namespace fra aura til nais

src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/config/MottakConfig.kt, src/main/kotlin/no/nav/familie/ef/søknad/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/MottakClient.kt, src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadController.kt, src/test/kotlin/no/nav/familie/ef/søknad/mock/MottakClientMock.kt, src/test/kotlin/no/nav/familie/ef/søknad/søknad/SøknadControllerTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24467)
- Fjerner de siste referansene til "søknadskvittering" i denne appen
NB. Kan ikke merges før mottak er oppdatert til å ta inn ny søknadsflyt via `/soknad`
=> skal fjerne siste rest av referanser mot søknadskvittering

.deploy/nais-dev.yaml, .deploy/nais-prod.yaml
Vil legge til observability + splitt. Midlertidig logg til både elastic og loki
=> Vil logge til både loki og elastic

src/main/kotlin/no/nav/familie/ef/søknad/søknad/SøknadService.kt
Det ser heldigvis ut til at maskering av fnr som ligger i nais-plattformen har virket.
=> Gjør om logging av fnr til securelogs. 
